
app:
    resource: '@AppBundle/Controller/'
    type: annotation

admin_area:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /manager

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /manager

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"